---
abstract: "Kulag's AniDB Renamer"
author:
  - 'Kulag <g.kulag@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
  Test::Exception: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-KADR
provides:
  App::KADR::AniDB::EpisodeNumber:
    file: lib/App/KADR/AniDB/EpisodeNumber.pm
    version: 0
  App::KADR::AniDB::EpisodeNumber::Range:
    file: lib/App/KADR/AniDB/EpisodeNumber/Range.pm
    version: 0
  App::KADR::AniDB::UDP::Client:
    file: lib/App/KADR/AniDB/UDP/Client.pm
    version: 0
  App::KADR::Config:
    file: lib/App/KADR/Config.pm
    version: 0
  App::KADR::Moose:
    file: lib/App/KADR/Moose.pm
    version: 0
  App::KADR::Moose::Role:
    file: lib/App/KADR/Moose/Role.pm
    version: 0
  App::KADR::Path:
    file: lib/App/KADR/Path.pm
    version: 0
  App::KADR::Path::Dir:
    file: lib/App/KADR/Path/Dir.pm
    version: 0
  App::KADR::Path::Entity:
    file: lib/App/KADR/Path/Entity.pm
    version: 0
  App::KADR::Path::File:
    file: lib/App/KADR/Path/File.pm
    version: 0
  App::KADR::Term::StatusLine:
    file: lib/App/KADR/Term/StatusLine.pm
    version: 0
  App::KADR::Term::StatusLine::Fractional:
    file: lib/App/KADR/Term/StatusLine/Fractional.pm
    version: 0
  App::KADR::Term::StatusLine::Freeform:
    file: lib/App/KADR/Term/StatusLine/Freeform.pm
    version: 0
  App::KADR::Util:
    file: lib/App/KADR/Util.pm
    version: 0
requires:
  Class::Load: 0
  DBD::SQLite: 0
  DBI: 0
  Digest::ED2K: 0
  Digest::MD4: 0
  Expect: 0
  File::Copy: 0
  File::Find: 0
  File::HomeDir: 0
  File::ShareDir: 1.00
  File::Spec::Memoized: 0
  Guard: 0
  Hook::AfterRuntime: 0
  List::AllUtils: 0
  Moose: 0
  Moose::Exporter: 0
  MooseX::Attribute::Chained: 0
  MooseX::Getopt: 0
  MooseX::SimpleConfig: 0
  MooseX::StrictConstructor: 0
  MooseX::Types::Stringlike: 0
  Sub::Exporter: 0
  Text::Xslate: 0
  YAML::XS: 0
  common::sense: 0
  enum: 0
  namespace::autoclean: 0
  perl: v5.14.0
  true::VERSION: 0
resources:
  license: http://opensource.org/licenses/ISC
  repository: https://github.com/Kulag/KADR
version: 1
